/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMiniExprScopeProvider extends DelegatingScopeProvider {
}
