/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MiniExprRuntimeModule extends AbstractMiniExprRuntimeModule {
}
