/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MiniExprStandaloneSetup extends MiniExprStandaloneSetupGenerated {

	public static void doSetup() {
		new MiniExprStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
