/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.gemoc.miniexpr.MiniExprRuntimeModule;
import org.gemoc.miniexpr.MiniExprStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiniExprIdeSetup extends MiniExprStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiniExprRuntimeModule(), new MiniExprIdeModule()));
	}
	
}
