/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.miniexpr.parser.antlr.internal.InternalMiniExprParser;
import org.gemoc.miniexpr.services.MiniExprGrammarAccess;

public class MiniExprParser extends AbstractAntlrParser {

	@Inject
	private MiniExprGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMiniExprParser createParser(XtextTokenStream stream) {
		return new InternalMiniExprParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MiniExprGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MiniExprGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
