/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.miniExpr;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.miniexpr.miniExpr.MiniExprPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
