/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.miniExpr;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.miniexpr.miniExpr.MiniExprPackage#getRef()
 * @model
 * @generated
 */
public interface Ref extends Expression
{
} // Ref
