/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.miniExpr;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vector Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.miniexpr.miniExpr.VectorConstant#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.gemoc.miniexpr.miniExpr.MiniExprPackage#getVectorConstant()
 * @model
 * @generated
 */
public interface VectorConstant extends Expression
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.miniexpr.miniExpr.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see org.gemoc.miniexpr.miniExpr.MiniExprPackage#getVectorConstant_Values()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getValues();

} // VectorConstant
