/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.miniexpr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MiniExprUiModule extends AbstractMiniExprUiModule {

	public MiniExprUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
